### ISSUE TITLE
Add `Membrane.RemoteStream` as caps for pads

### ISSUE THREAD

**Issue by bblaszkow06** [membraneframework/membrane_file_plugin#21]
- [x] Send `RemoteStream` from source
  - The caps sent from the source may include a remote stream type - either auto-detected from file extension or set via option
- [ ] Change pad caps in source and sinks

**Comment by Rados13** [comment]
What about `H264.RemoteStream` caps?

**Comment by bblaszkow06** [comment]
Sources use `Membrane.RemoteStream` now, for sinks caps should be left as `:any` for now.
