### ISSUE TITLE
Sink should merge temporary file and close the main one on end of stream event

### ISSUE THREAD

**Issue by gBillal** [membraneframework/membrane_file_plugin#37]
Currently the `Membrane.File.Sink` only merge temporary file with the main file and close it when it receives a `terminate` event. Shouldn't it do the same when it receives an `end_of_stream` since the pad will not be used anymore.

```elixir
@impl true
def handle_end_of_stream(:input, _ctx, state) do
  state = maybe_merge_temporary(state)
  @common_file.close!(state.fd)

  {[], %{state | fd: nil}}
end
```

 <hr/>

In my case, I save a mp4 file with `fast start` to a temporary file and send it to a remote store. I send the temporary file after receiving `element_end_of_stream` event in the main pipeline and then terminate the children. At this point the MP4 file is not yet merged and closed. Of course there's a workaround like sending a message to the pipeline, terminate the children and then processing the sent message. However I think it's more appropriate to do it in the sink.

**Comment by DominikWolek** [comment]
I guess, yeah, you're right. Can you open a Pull request? Or would you like somebody of the team take care of it?

**Comment by gBillal** [comment]
@DominikWolek no problem, I'll create a PR for this issue

**Comment by DominikWolek** [comment]
Great!
